
Requirements   
We are required to use the dataset contained within the file “vgsales.csv” and then answer the following questions using a different visualization type (eg. Bar Chart, Scatter graph etc…) for each question: 
 
•	What are the top 5 games by global sales?   
•	What is the distribution of the most popular 4 game genres?  
•	Do older games (2006 and earlier) have a higher MEDIAN “eu_sales” than newer games (after 2006)?  
•	What are the 3 most common “developer” in the dataset?  

We must incorporate the following elements:
A Jupyter Notebook detailing your 
EDA process, 
Data Cleaning,
Feature Selection
Data Visualizations

In [11]:
# installing necessary libraries
!pip install pandas seaborn
!pip install plotly

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

Requirement already satisfied: pandas in c:\users\arkje\appdata\local\programs\python\python312\lib\site-packages (3.0.1)
Requirement already satisfied: seaborn in c:\users\arkje\appdata\local\programs\python\python312\lib\site-packages (0.13.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\arkje\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\arkje\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\arkje\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\arkje\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\arkje\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\arkje\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\arkje\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\arkje\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\arkje\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\arkje\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\arkje\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\arkje\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: plotly in c:\users\arkje\appdata\local\programs\python\python312\lib\site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\arkje\appdata\local\programs\python\python312\lib\site-packages (from plotly) (2.21.2)
Requirement already satisfied: packaging in c:\users\arkje\appdata\roaming\python\python312\site-packages (from plotly) (26.0)

[notice] A new release of pip is available: 23.2.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# loading the dataset and displaying the first few rows
df = pd.read_csv('../DATASETS/vgsales.csv')
df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# displaying the last few (2) rows of the dataset
df.tail(2)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.0,0.00,0.0,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.0,0.01,0.0,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# -- SECTION EDA (Exploratory Data Analysis) --
# basic information about the dataset

df.shape          # volume of data
df.info()         # data types and non-null counts
df.describe()     # statistics
df.isnull().sum() # missing values

<class 'pandas.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  str
 1   Platform         16719 non-null  str
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  str
 4   Publisher        16665 non-null  str
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Other_Sales      16719 non-null  float64
 9   Global_Sales     16719 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   float64
 12  User_Score       10015 non-null  str
 13  User_Count       7590 non-null   float64
 14  Developer        10096 non-null  str
 15  Rating           9950 non-null   str
dtypes: float64(9), str(7)
memory usage: 2.0 MB

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       8582
Critic_Count       8582
User_Score         6704
User_Count         9129
Developer          6623
Rating             6769
dtype: int64

We can see important columns:
- name
- platform
- year_of_release
- genre
- eu_sales
- global_sales
- developer

In [15]:
# data cleaning
df.dropna(inplace=True)
df['Year_of_Release'] = df['Year_of_Release'].astype(int)
df.drop_duplicates(inplace=True)